[Interface]
PrivateKey = eDyokvhnUuFsnTbPYyIdqy8C9nAP6dofafCoSDI1B1w=
Address = 10.0.15.8/32

[Peer]
PublicKey = 0+rMmJZ3ZBAQUWmfnWDRJ2UZ1JCnFXHbOxPbVQQkkSs=
Endpoint = 172.17.62.1:51820
AllowedIPs = 0.0.0.0/0,::/0
PersistentKeepalive = 25
